name: water_cloud_body
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - chromadb>=0.5.11
      - openai>=1.100.1
      - requests>=2.32.4
      - beautifulsoup4>=4.13.3
      - python-dotenv>=1.1.1
      - tenacity>=8.5.0
